# Generated by Django 4.2.11 on 2026-07-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_category_icon_productreview"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(default="ETH Imports", max_length=100)),
                (
                    "header_tagline",
                    models.CharField(
                        blank=True,
                        default="Premium Ethiopian Imported Products",
                        max_length=200,
                    ),
                ),
                ("hero_badge", models.CharField(default="Summer Sale", max_length=100)),
                (
                    "hero_title",
                    models.CharField(
                        default="Discover Premium Ethiopian Imports", max_length=200
                    ),
                ),
                (
                    "hero_subtitle",
                    models.TextField(
                        default="Curated collection of high-quality products from around the world, delivered to your doorstep."
                    ),
                ),
                (
                    "hero_button_text",
                    models.CharField(default="Shop Now", max_length=50),
                ),
                (
                    "hero_button_url",
                    models.CharField(default="#products", max_length=200),
                ),
                (
                    "hero_secondary_button_text",
                    models.CharField(default="Watch Story", max_length=50),
                ),
                (
                    "hero_secondary_button_url",
                    models.CharField(default="#", max_length=200),
                ),
                (
                    "categories_title",
                    models.CharField(default="Shop by Category", max_length=100),
                ),
                (
                    "categories_view_all",
                    models.CharField(default="View All", max_length=50),
                ),
                (
                    "footer_brand",
                    models.CharField(default="ETH Imports", max_length=100),
                ),
                (
                    "footer_tagline",
                    models.CharField(
                        default="Premium products for discerning customers. Curated with care, delivered with excellence.",
                        max_length=200,
                    ),
                ),
                (
                    "footer_copyright",
                    models.CharField(default="All rights reserved.", max_length=200),
                ),
                (
                    "whatsapp_number",
                    models.CharField(default="+251900000000", max_length=20),
                ),
                (
                    "telegram_username",
                    models.CharField(default="your_username", max_length=50),
                ),
                ("facebook_url", models.URLField(blank=True, default="#")),
                ("instagram_url", models.URLField(blank=True, default="#")),
                ("twitter_url", models.URLField(blank=True, default="#")),
                ("youtube_url", models.URLField(blank=True, default="#")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
    ]
