# Generated by Django 4.2.11 on 2026-07-16 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_sitesettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="brand_suffix",
            field=models.CharField(
                default=" Imports",
                help_text='Text after ETH (e.g., " Imports")',
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="eth_e_color",
            field=models.CharField(
                default="#0F8B4C", help_text='Color for "E" in ETH', max_length=20
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="eth_h_color",
            field=models.CharField(
                default="#EF4444", help_text='Color for "H" in ETH', max_length=20
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="eth_t_color",
            field=models.CharField(
                default="#F6B100", help_text='Color for "T" in ETH', max_length=20
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="eth_text",
            field=models.CharField(
                default="ETH", help_text="Main logo text (e.g., ETH)", max_length=10
            ),
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="product_images/")),
                ("alt_text", models.CharField(blank=True, max_length=200)),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Set as main product image"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Display order"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Image",
                "verbose_name_plural": "Product Images",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
