# Generated by Django 4.2.11 on 2026-07-19 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0004_sitesettings_brand_suffix_sitesettings_eth_e_color_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Category image for display",
                null=True,
                upload_to="categories/",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text="Font Awesome icon class (e.g., 'fas fa-laptop')",
                max_length=50,
            ),
        ),
    ]
